/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../app/app.module.server';
import * as i2 from '../../app/app.component';
import * as i3 from './app.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/platform-browser';
import * as i6 from '@angular/platform-server';
import * as i7 from '@angular/animations/browser';
import * as i8 from '@angular/platform-browser/animations';
import * as i9 from '@angular/http';
import * as i10 from '@angular/common/http';
import * as i11 from '@angular/animations';
export const AppModuleServerNgFactory:i0.NgModuleFactory<i1.AppModuleServer> = i0.ɵcmf(i1.AppModuleServer,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i4.NgLocalization,
              i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i5.DomSanitizer,
              i5.ɵe,[i4.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i5.DomSanitizer]),
          i0.ɵmpd(4608,i5.HAMMER_GESTURE_CONFIG,i5.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i5.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i5.ɵDomEventsPlugin(p0_0),new i5.ɵKeyEventsPlugin(p1_0),new i5.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i4.DOCUMENT,i4.DOCUMENT,i4.DOCUMENT,i5.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i5.EventManager,i5.EventManager,[i5.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i5.ɵDomSharedStylesHost,i5.ɵDomSharedStylesHost,[i4.DOCUMENT]),
          i0.ɵmpd(4608,i5.ɵDomRendererFactory2,i5.ɵDomRendererFactory2,[i5.EventManager,
              i5.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i6.ɵb,i6.ɵb,[i5.DOCUMENT,[2,i5.ɵTRANSITION_ID]]),
          i0.ɵmpd(6144,i5.ɵSharedStylesHost,(null as any),[i6.ɵb]),i0.ɵmpd(4608,i6.ɵServerRendererFactory2,
              i6.ɵServerRendererFactory2,[i0.NgZone,i5.DOCUMENT,i5.ɵSharedStylesHost]),
          i0.ɵmpd(4608,i7.AnimationDriver,i7.ɵNoopAnimationDriver,([] as any[])),i0.ɵmpd(5120,
              i7.ɵAnimationStyleNormalizer,i8.ɵd,([] as any[])),i0.ɵmpd(4608,i7.ɵAnimationEngine,
              i8.ɵb,[i7.AnimationDriver,i7.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,
              i0.RendererFactory2,i6.ɵa,[i6.ɵServerRendererFactory2,i7.ɵAnimationEngine,
                  i0.NgZone]),i0.ɵmpd(4352,i0.Testability,(null as any),([] as any[])),
          i0.ɵmpd(4608,i5.Meta,i5.Meta,[i4.DOCUMENT]),i0.ɵmpd(4608,i5.Title,i5.Title,
              [i4.DOCUMENT]),i0.ɵmpd(4608,i9.BrowserXhr,i6.ɵc,([] as any[])),i0.ɵmpd(4608,
              i9.ResponseOptions,i9.BaseResponseOptions,([] as any[])),i0.ɵmpd(4608,
              i9.XSRFStrategy,i6.ɵd,([] as any[])),i0.ɵmpd(4608,i9.XHRBackend,i9.XHRBackend,
              [i9.BrowserXhr,i9.ResponseOptions,i9.XSRFStrategy]),i0.ɵmpd(4608,i9.RequestOptions,
              i9.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i9.Http,i6.ɵe,[i9.XHRBackend,
              i9.RequestOptions]),i0.ɵmpd(4608,i10.HttpXsrfTokenExtractor,i10.ɵg,[i4.DOCUMENT,
              i0.PLATFORM_ID,i10.ɵe]),i0.ɵmpd(4608,i10.ɵh,i10.ɵh,[i10.HttpXsrfTokenExtractor,
              i10.ɵf]),i0.ɵmpd(5120,i10.HTTP_INTERCEPTORS,(p0_0:any) => {
            return [p0_0];
          },[i10.ɵh]),i0.ɵmpd(4608,i10.XhrFactory,i6.ɵc,([] as any[])),i0.ɵmpd(4608,
              i10.HttpXhrBackend,i10.HttpXhrBackend,[i10.XhrFactory]),i0.ɵmpd(6144,
              i10.HttpBackend,(null as any),[i10.HttpXhrBackend]),i0.ɵmpd(5120,i10.HttpHandler,
              i6.ɵf,[i10.HttpBackend,[2,i10.HTTP_INTERCEPTORS]]),i0.ɵmpd(4608,i10.HttpClient,
              i10.HttpClient,[i10.HttpHandler]),i0.ɵmpd(4608,i10.ɵd,i10.ɵd,([] as any[])),
          i0.ɵmpd(4608,i11.AnimationBuilder,i8.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i5.ɵa,([] as any[])),i0.ɵmpd(256,i0.APP_ID,'ssr-ng-seed',
              ([] as any[])),i0.ɵmpd(2048,i5.ɵTRANSITION_ID,(null as any),[i0.APP_ID]),
          i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any,p1_1:any,p1_2:any) => {
            return [i5.ɵc(p0_0,p0_1),i5.ɵf(p1_0,p1_1,p1_2)];
          },[[2,i5.NgProbeToken],[2,i0.NgProbeToken],i5.ɵTRANSITION_ID,i4.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i5.BrowserModule,
              i5.BrowserModule,[[3,i5.BrowserModule]]),i0.ɵmpd(512,i9.HttpModule,i9.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i10.HttpClientXsrfModule,i10.HttpClientXsrfModule,
              ([] as any[])),i0.ɵmpd(512,i10.HttpClientModule,i10.HttpClientModule,
              ([] as any[])),i0.ɵmpd(512,i8.NoopAnimationsModule,i8.NoopAnimationsModule,
              ([] as any[])),i0.ɵmpd(512,i6.ServerModule,i6.ServerModule,([] as any[])),
          i0.ɵmpd(512,i1.AppModuleServer,i1.AppModuleServer,([] as any[])),i0.ɵmpd(256,
              i10.ɵe,'XSRF-TOKEN',([] as any[])),i0.ɵmpd(256,i10.ɵf,'X-XSRF-TOKEN',
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2lsaWFpZGFraWV2L0RvY3VtZW50cy9kZXYvc3NyLW5nLXNlZWQvc3JjL2FwcC9hcHAubW9kdWxlLnNlcnZlci5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9pbGlhaWRha2lldi9Eb2N1bWVudHMvZGV2L3Nzci1uZy1zZWVkL3NyYy9hcHAvYXBwLm1vZHVsZS5zZXJ2ZXIudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
